// sorry-card, valentine-ask, birthday-wish — the three templates users
// actually love, expressed as config.
//
// The pre/post block phases are what let the bespoke components go away:
// `SorryCard` and `ValentineCard` are the same growing-YES / stubborn-NO game
// wrapped in different copy, and `BirthdayCard` is the same shape with a cake
// instead of a button. Roughly 350 duplicated lines collapse into two widgets.

import type { ThemeDraft } from "../types";

export const sorryTheme: ThemeDraft = {
  id: "sorry-card",
  name: "I'm Sorry",
  palette: {
    primary: "#3b82f6",
    secondary: "#bfdbfe",
    accent: "#1d4ed8",
    ink: "#1e293b",
    paper: "#fbfdff",
    glow: "#c7d2fe",
  },
  surface: { kind: "glass", tint: "secondary", shine: true },
  frame: { kind: "rounded", radiusPx: 24, shadow: "xl" },
  layout: "centered-card",
  ambient: {
    enabled: true,
    blobs: [
      {
        anchor: "top-left",
        sizePx: 600,
        color: "#fbcfe8",
        opacity: 0.4,
        durationSec: 8,
      },
      {
        anchor: "bottom-right",
        sizePx: 500,
        color: "#e9d5ff",
        opacity: 0.4,
        durationSec: 10,
      },
    ],
  },
  // The whole emotional arc of this card, as two decor entries: it rains
  // until you are forgiven, then it rains hearts.
  decor: [
    {
      kind: "float",
      phase: "pre",
      count: 14,
      glyphs: ["💧", "💔"],
      direction: "down",
      speedSec: [2, 5],
      sizeRem: 1.5,
      opacity: 0.3,
    },
    {
      kind: "float",
      phase: "post",
      count: 14,
      glyphs: ["💖", "🥰", "✨", "🌸"],
      direction: "up",
      speedSec: [4, 7],
      sizeRem: 1.875,
      opacity: 0.4,
    },
    {
      kind: "burst",
      phase: "post",
      count: 24,
      colors: ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff"],
      shape: "circle",
      spreadPx: 600,
      repeatDelaySec: 2,
    },
  ],
  motion: {
    intro: "rise",
    introDelayMs: 0,
    staggerMs: 90,
    reveal: "lines",
    revealStepMs: 380,
  },
  blocks: [
    { type: "hero", phase: "pre", media: { kind: "emoji", value: "🥺", sizeRem: 6 } },
    { type: "title", phase: "pre", text: "I'm So Sorry", color: "primary", size: "xl" },
    { type: "subtitle", phase: "pre", field: "recipientName", fallback: "Dear Friend" },
    { type: "body", phase: "pre", field: "reason", fallback: "everything", prefix: "for" },
    { type: "quote", phase: "pre", field: "promise", prefix: "I promise to" },
    {
      type: "eyebrow",
      phase: "pre",
      text: "Please find it in your heart to forgive me.",
    },

    {
      type: "hero",
      phase: "post",
      media: {
        kind: "gif",
        src: "https://media1.tenor.com/m/cOjBPqUGt4MAAAAC/bear-hug.gif",
        alt: "Bear Hug Sticker",
        width: 250,
        height: 250,
        maxWidthPx: 250,
      },
    },
    { type: "title", phase: "post", text: "Yippeee!!", color: "#ec4899", size: "xl" },
    {
      type: "body",
      phase: "post",
      text: "Thank you for forgiving me!\nYou're the absolute best.",
    },
    { type: "cta", phase: "post", label: "Send One Back", href: "/templates" },
    {
      type: "signature",
      phase: "post",
      field: "senderName",
      prefix: "—",
      fallback: "Sincerely Sorry",
    },
  ],
  interaction: {
    kind: "yes-no-game",
    yesLabel: "Yes, I Forgive You",
    growthPx: 20,
    maxYesPx: 60,
    noPhrases: [
      "No",
      "Are you sure?",
      "Really sure?",
      "Think again!",
      "Last chance!",
      "Surely not?",
      "You might regret this!",
      "Give me a chance!",
      "Have a heart!",
      "Don't be so cold!",
      "Change of heart?",
      "Wouldn't you reconsider?",
      "Is that your final answer?",
      "You're breaking my heart ;(",
    ],
  },
  envelope: {
    enabled: true,
    sealEmoji: "🥺",
    hint: "Tap to open",
    paperColor: "#dbeafe",
    flapColor: "primary",
    liningColor: "#fbfdff",
  },
};

export const valentineTheme: ThemeDraft = {
  id: "valentine-ask",
  name: "Be My Valentine?",
  palette: {
    primary: "#e11d48",
    secondary: "#fecdd3",
    accent: "#be123c",
    ink: "#3f1a24",
    paper: "#fffafb",
    glow: "#fda4af",
  },
  surface: { kind: "glass", tint: "secondary", shine: true },
  frame: { kind: "rounded", radiusPx: 24, shadow: "xl" },
  layout: "centered-card",
  ambient: {
    enabled: true,
    blobs: [
      {
        anchor: "top-left",
        sizePx: 600,
        color: "#f9a8d4",
        opacity: 0.4,
        durationSec: 8,
      },
      {
        anchor: "bottom-right",
        sizePx: 500,
        color: "#fca5a5",
        opacity: 0.4,
        durationSec: 10,
      },
    ],
  },
  decor: [
    {
      kind: "float",
      phase: "always",
      count: 14,
      glyphs: ["❤️", "💖", "💘", "💓", "💕"],
      direction: "up",
      speedSec: [10, 20],
      sizeRem: 1.5,
      opacity: 0.3,
    },
    {
      kind: "burst",
      phase: "post",
      count: 24,
      colors: ["#ff0000", "#ff69b4", "#ffffff", "#ff1493"],
      shape: "circle",
      spreadPx: 800,
      repeatDelaySec: 3,
    },
  ],
  motion: {
    intro: "rise",
    introDelayMs: 0,
    staggerMs: 90,
    reveal: "lines",
    revealStepMs: 380,
  },
  blocks: [
    {
      type: "hero",
      phase: "pre",
      media: { kind: "emoji", value: "💝", sizeRem: 6, pulse: true },
    },
    {
      type: "title",
      phase: "pre",
      text: "Will you be my Valentine?",
      color: "primary",
      size: "xl",
    },
    { type: "subtitle", phase: "pre", field: "recipientName", fallback: "My Love" },
    {
      type: "quote",
      phase: "pre",
      field: "reason",
      fallback: "You make my world brighter every single day.",
    },

    {
      type: "hero",
      phase: "post",
      media: {
        kind: "gif",
        src: "https://media1.tenor.com/m/D1CAg1rBD6wAAAAC/tkthao219-bubududu.gif",
        alt: "Tkthao219 Bubududu Sticker",
        width: 250,
        height: 250,
        maxWidthPx: 250,
      },
    },
    {
      type: "title",
      phase: "post",
      text: "Wooohooo!!! 💖",
      color: "primary",
      size: "xl",
    },
    {
      type: "body",
      phase: "post",
      text: "I knew you'd say yes!\nCan't wait for our special day.",
    },
    { type: "cta", phase: "post", label: "Ask Someone Special", href: "/templates" },
    {
      type: "signature",
      phase: "post",
      field: "senderName",
      prefix: "With endless love,",
      fallback: "Admirer",
    },
  ],
  interaction: {
    kind: "yes-no-game",
    yesLabel: "YES! 💖",
    growthPx: 20,
    maxYesPx: 60,
    evadeNo: true,
    noPhrases: [
      "No",
      "Are you sure?",
      "Think again!",
      "Please?",
      "Really?",
      "Don't do this!",
      "I'll be sad!",
      "Give me a chance!",
      "Pretty please?",
      "My heart...",
      "Think about it!",
      "Last chance!",
    ],
  },
  envelope: {
    enabled: true,
    sealEmoji: "💝",
    hint: "Someone has a question for you",
    paperColor: "#ffe4e6",
    flapColor: "primary",
    liningColor: "#fffafb",
  },
};

export const birthdayTheme: ThemeDraft = {
  id: "birthday-wish",
  name: "Birthday Wish",
  palette: {
    primary: "#f59e0b",
    secondary: "#fde68a",
    accent: "#d97706",
    ink: "#3b2f1a",
    paper: "#fffdf6",
    glow: "#fcd34d",
  },
  surface: { kind: "glass", tint: "secondary", shine: true },
  frame: { kind: "rounded", radiusPx: 24, shadow: "2xl" },
  layout: "centered-card",
  ambient: {
    enabled: true,
    blobs: [
      {
        anchor: "top-left",
        sizePx: 600,
        color: "#93c5fd",
        opacity: 0.3,
        durationSec: 10,
      },
      {
        anchor: "bottom-right",
        sizePx: 600,
        color: "#d8b4fe",
        opacity: 0.3,
        durationSec: 12,
        delaySec: 2,
      },
    ],
  },
  decor: [
    {
      kind: "float",
      phase: "always",
      count: 12,
      glyphs: ["🎈"],
      direction: "up",
      speedSec: [15, 25],
      sizeRem: 3,
      opacity: 0.6,
      variant: "balloon",
      tints: ["#ff718d", "#fdb66d", "#71e5ff", "#9d71ff", "#ffeb71"],
    },
    {
      kind: "burst",
      phase: "post",
      count: 24,
      colors: ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff"],
      shape: "square",
      spreadPx: 800,
      repeatDelaySec: 3,
    },
  ],
  motion: {
    intro: "spring-pop",
    introDelayMs: 0,
    staggerMs: 100,
    reveal: "lines",
    revealStepMs: 380,
  },
  blocks: [
    { type: "title", phase: "pre", text: "Make a Wish!", size: "lg" },
    {
      type: "eyebrow",
      phase: "pre",
      text: "Tap the cake to blow out the candles",
    },

    {
      type: "hero",
      phase: "post",
      media: {
        kind: "gif",
        src: "https://media1.tenor.com/m/tPJaogUqo8wAAAAC/happy-birthday.gif",
        alt: "Happy Birthday GIF",
        width: 280,
        height: 280,
        maxWidthPx: 280,
      },
    },
    // Was a rotated pink badge pinned to the corner of the GIF; a pill under
    // it survives a data-driven layout and reads the same.
    { type: "badge", phase: "post", field: "age", emoji: "🎉", suffix: " today" },
    { type: "title", phase: "post", text: "Happy Birthday", size: "xl" },
    {
      type: "subtitle",
      phase: "post",
      field: "recipientName",
      fallback: "Friend",
      suffix: "!",
    },
    {
      type: "body",
      phase: "post",
      field: "message",
      fallback: "Wishing you a wonderful day!",
      paced: true,
    },
    {
      type: "highlight",
      phase: "post",
      field: "wish",
      label: "A Special Wish",
      color: "#db2777",
    },
    { type: "cta", phase: "post", label: "Send One Too", href: "/templates" },
    { type: "replay", phase: "post", label: "Replay" },
    {
      type: "signature",
      phase: "post",
      field: "senderName",
      prefix: "—",
      fallback: "Your Friend",
    },
  ],
  interaction: {
    kind: "blow-candles",
    candles: 3,
    hint: "Tap the cake to blow out the candles",
    smokeMs: 1500,
    replayable: true,
  },
  envelope: {
    enabled: true,
    sealEmoji: "🎂",
    hint: "Tap to open your birthday card",
    paperColor: "#fef3c7",
    flapColor: "primary",
    liningColor: "#fffdf6",
  },
};
