"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "motion/react";

export default function TermsPage() {
  return (
    <div className="min-h-screen font-sans bg-pink-50/30">
      <Navbar />

      <main className="pt-32 pb-16 px-6 lg:px-12">
        <div className="max-w-4xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-xl shadow-pink-100/50 border border-pink-100">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="text-3xl md:text-5xl font-serif font-bold text-gray-900 mb-8 text-center">
              Terms & <span className="text-pink-600">Conditions</span>
            </h1>

            <div className="prose prose-pink prose-lg max-w-none text-gray-600 leading-relaxed">
              <p className="lead text-xl text-gray-700 font-medium mb-8">
                Welcome to LetterLove! By using our website and services, you
                agree to the following terms. We want to keep things simple,
                transparent, and safe for everyone.
              </p>

              <h3 className="text-2xl font-serif font-bold text-gray-800 mt-8 mb-4">
                1. Use of Service
              </h3>
              <p>
                LetterLove provides AI-powered tools to help you generate text
                content ("letters"). You are free to use these letters for
                personal purposes. You agree not to use our service to generate
                content that is hateful, abusive, illegal, or harmful to others.
              </p>

              <h3 className="text-2xl font-serif font-bold text-gray-800 mt-8 mb-4">
                2. User-Generated Links & Content
              </h3>
              <div className="bg-red-50 border-l-4 border-red-400 p-6 rounded-r-xl my-6">
                <p className="font-bold text-red-800 mb-2">
                  Important Disclaimer regarding Shared Links:
                </p>
                <p className="text-red-700 text-base">
                  Our service allows users to generate unique links to share
                  their letters with others.{" "}
                  <strong>
                    LetterLove is NOT responsible for the content, safety, or
                    intent of any link sent to you by a third party.
                  </strong>{" "}
                  If you receive a LetterLove link from someone, you open it at
                  your own discretion. We do not monitor or control who sends
                  links to whom. We assume no legal liability or responsibility
                  for any consequences arising from opening links shared by
                  other users.
                </p>
              </div>

              <h3 className="text-2xl font-serif font-bold text-gray-800 mt-8 mb-4">
                3. AI Limitations
              </h3>
              <p>
                Our letters are generated by Artificial Intelligence (Eugene).
                While we strive for quality, AI can sometimes produce unexpected
                or inaccurate results. Please review all generated content
                before sharing it. We are not liable for any misunderstandings
                or issues resulting from the text generated.
              </p>

              <h3 className="text-2xl font-serif font-bold text-gray-800 mt-8 mb-4">
                4. Intellectual Property
              </h3>
              <p>
                The designs, code, and branding of LetterLove are owned by us.
                The text you generate is yours to use personally.
              </p>

              <h3 className="text-2xl font-serif font-bold text-gray-800 mt-8 mb-4">
                5. Changes to Terms
              </h3>
              <p>
                We may update these terms from time to time. Continued use of
                the site implies acceptance of the new terms.
              </p>

              <div className="mt-12 pt-8 border-t border-gray-100 text-center text-sm text-gray-500">
                Last Updated:{" "}
                {new Date().toLocaleDateString("en-US", {
                  month: "long",
                  day: "numeric",
                  year: "numeric",
                })}
              </div>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
